services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email gilee@student.42seoul.kr --agree-tos --no-eff-email -d server.gilee.click
    restart: "no"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    ports:
      - "${DB_HOST_PORT}:5432"

  api:
    container_name: api
    build: ./api
    volumes:
      - ./logs/api/:/log
    expose:
      - "3000"